Repository Arquisoft/lomap_es6c, pull requests merged in 2023-02, with the labels that each got.

#3 Apartado de stakeholders hecho
  docs/01_introduction_and_goals.adoc
Labels: documentation

#5 Apartados 1.1 y 1.2 acabados
  docs/01_introduction_and_goals.adoc
Labels: documentation

#6 Apartado 2 - Restricciones de Arquitectura
  docs/02_architecture_constraints.adoc
Labels: documentation

#7 Diagrams for 'System scope and context' docu
  docs/images/business_context.png
  docs/images/technical_context.png
Labels: documentation

#9 Documentation develop
  docs/03_system_scope_and_context.adoc
  docs/images/business_context.png
  docs/images/technical_context.png
Labels: documentation

#20 Revert "Update 'System and Context' documentation"
  docs/03_system_scope_and_context.adoc
Labels: 📖documentation

#24 Apartado 10 documentacion completado
  docs/03_system_scope_and_context.adoc
  docs/10_quality_scenarios.adoc
  docs/images/QualityTree.png
Labels: 📖documentation

#26 apartado 7 documentación
  docs/07_deployment_view.adoc
Labels: 📖documentation

#27 Apartado 4 de la documentacion
  docs/04_solution_strategy.adoc
  docs/07_deployment_view.adoc
Labels: 📖documentation

#25 Apartado 6 documentación
  docs/06_runtime_view.adoc
  docs/images/addMarker.png
  docs/images/filter.png
  docs/images/login.png
  docs/images/removeMarker.png
  docs/images/shareMarker.png
Labels: 📖documentation

#29 Apartado 8 de la documentación
  docs/06_runtime_view.adoc
  docs/08_concepts.adoc
  docs/11_technical_risks.adoc
  docs/images/addMarker.png
  docs/images/domain_model.png
  docs/images/filter.png
  docs/images/login.png
  docs/images/removeMarker.png
  docs/images/shareMarker.png
Labels: 📖documentation

#19 Apartado 5. Building Block View
  docs/05_building_block_view.adoc
Labels: 📖 documentation

#32 Puntos 9 y 12
  docs/09_design_decisions.adoc
  docs/12_glossary.adoc
Labels: 📖 documentation

#23 Implementación OpenStreetMaps
  restapi/api.ts
  webapp/.gitignore
  webapp/README copy.md
  webapp/README.md
  webapp/e2e/features/register-form.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/register-form.steps.ts
  webapp/jest.config.ts
  webapp/loadtestexample/GetUsersList.scala
  webapp/loadtestexample/getuserslist/0004_request.txt
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/App.css
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/components/Welcome.test.tsx
  webapp/src/components/Welcome.tsx
  webapp/src/index.tsx
  webapp/src/shared/shareddtypes.ts
  webapp/tsconfig.json
Labels: 🎨 frontend
