Repository Arquisoft/lomap_es6c, pull requests merged in 2023-03, with the labels that each got.

#31 Nuevo icono y tocar un poco el readme
  README.md
  docs/images/lomap-icon.png
  docs/images/lomapicon.png
Labels: 📖 documentation

#41 Implementar base de datos
  docker-compose.yml
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  restapi/src/api.ts
  restapi/src/database/database.ts
Labels: 🛠️ backend, 📚 persistency

#40 Documentación
  README.md
  docs/images/lomap-icon.png
  docs/images/lomapicon.png
Labels: 📖 documentation

#45 Frontend empezar
  README.md
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/QualityTree.png
  docs/images/addMarker.png
  docs/images/domain_model.png
  docs/images/filter.png
  docs/images/login.png
  docs/images/lomap-icon.png
  docs/images/lomapicon.png
  docs/images/removeMarker.png
  docs/images/shareMarker.png
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/Footer/Footer.css
  webapp/src/components/Footer/Footer.tsx
  webapp/src/components/MainMenu/MainMenu.css
  webapp/src/components/MainMenu/MainMenu.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/NavBar/NavBar.css
  webapp/src/components/NavBar/NavBar.tsx
  webapp/src/components/WelcomePage/WelcomePage.css
  webapp/src/components/WelcomePage/WelcomePage.tsx
  webapp/src/images/lomap-icon.png
Labels: 🎨 frontend

#46 CRUD markers
  docker-compose.yml
  restapi/src/api.ts
  restapi/src/database/database.ts
  webapp/src/api/api.ts
  webapp/src/components/Map/OSMap.tsx
Labels: 🛠️ backend, 📚 persistency

#52 Actualización - Caja blanca Front-end
  docs/05_building_block_view.adoc
Labels: 📖 documentation

#58 Update 01_introduction_and_goals.adoc
  docs/01_introduction_and_goals.adoc
Labels: 📖 documentation, 🔧fixed

#59 Actualizacion del punto 4 de la documentacion
  docs/04_solution_strategy.adoc
Labels: 📖 documentation, 🔧fixed

#56 Saul comments
  webapp/src/components/Map/OSMap.tsx
Labels: 🎨 frontend, 🔧fixed

#64 Update docu 6
  docs/images/login.png
Labels: 📖 documentation, 🔧fixed

#61 Toda la docu actualizada
  docs/01_introduction_and_goals.adoc
  docs/04_solution_strategy.adoc
  docs/images/login.png
Labels: 📖 documentation

#68 Solid LOGIN
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/User/UserLogin.tsx
Labels: solid, 🔧fixed

#73 Redo login page and prepare app for login status
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/LoginPage/LoginPage.tsx
  webapp/src/components/NavBar/NavBar.tsx
  webapp/src/components/SignupPage/SignupPage.css
  webapp/src/components/SignupPage/SignupPage.tsx
  webapp/src/components/User/ProfileViewer.tsx
  webapp/src/components/User/UserLogin.tsx
  webapp/src/components/WelcomePage/WelcomePage.css
  webapp/src/components/WelcomePage/WelcomePage.tsx
  webapp/src/components/WelcomePage/subcomponents/WelcomeText.tsx
  webapp/src/components/pages/LoginPage/LoginPage.css
  webapp/src/components/pages/LoginPage/LoginPage.tsx
  webapp/src/components/pages/MainMenu/MainMenu.css
  webapp/src/components/pages/MainMenu/MainMenu.tsx
  webapp/src/components/pages/UserPage/UserPage.tsx
Labels: 🎨 frontend, solid, 🔧fixed

#75 Implement mongo-express
  docker-compose.yml
Labels: 🦾 enhancement, 📚 persistency, 🔧fixed, 🐳 dockerizing

#67 Develop to master
  docker-compose.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/LoginPage/LoginPage.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/NavBar/NavBar.tsx
  webapp/src/components/SignupPage/SignupPage.css
  webapp/src/components/SignupPage/SignupPage.tsx
  webapp/src/components/User/ProfileViewer.tsx
  webapp/src/components/User/UserLogin.tsx
  webapp/src/components/WelcomePage/WelcomePage.css
  webapp/src/components/WelcomePage/WelcomePage.tsx
  webapp/src/components/WelcomePage/subcomponents/WelcomeText.tsx
  webapp/src/components/pages/LoginPage/LoginPage.css
  webapp/src/components/pages/LoginPage/LoginPage.tsx
  webapp/src/components/pages/MainMenu/MainMenu.css
  webapp/src/components/pages/MainMenu/MainMenu.tsx
  webapp/src/components/pages/UserPage/UserPage.tsx
Labels: 🦾 enhancement

#87 Comments layout
  webapp/src/components/CommentsPage/CommentsPage.css
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/OSMap.tsx
Labels: 🎨 frontend, 🔧fixed

#89 Frontend profileview
  webapp/src/components/User/ProfileViewer.tsx
  webapp/src/components/User/UserLogin.tsx
  webapp/src/components/pages/LoginPage/LoginPage.css
Labels: 🎨 frontend

#90 Ajuste WelcomePage
  webapp/src/components/WelcomePage/WelcomePage.css
  webapp/src/components/WelcomePage/WelcomePage.tsx
Labels: 🎨 frontend

#88 Escribir en pod de uno mismo o en el que tenga autorización
  docs/01_introduction_and_goals.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/images/login.png
  package-lock.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/Friends/WriteInputToPod.tsx
  webapp/src/components/Solid/User/ProfileViewer.tsx
  webapp/src/components/Solid/User/UserLogin.tsx
  webapp/src/components/Solid/WriteToPod.ts
  webapp/src/components/pages/LoginPage/LoginPage.css
  webapp/src/components/pages/LoginPage/LoginPage.tsx
  webapp/src/components/pages/MainMenu/MainMenu.tsx
  webapp/src/components/pages/UserPage/UserPage.tsx
Labels: 🔒 solid
