Repository Arquisoft/lomap_es6c, pull requests merged in 2023-04, with the labels that each got.

#102 Guardar marcador en el pod
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/Friends/WriteInputToPod.tsx
  webapp/src/components/Solid/WriteToPod.ts
Labels: 🎨 frontend, 🛠️ backend, 🔒 solid, 🔧fixed

#96 Integración continua
  .github/workflows/lomap_es6c.yml
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/Friends/WriteInputToPod.tsx
Labels: 🔧fixed, 🐳 dockerizing, CI

#95 Arreglo de amigos para que reenvie a inrupt
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/Friends/WriteInputToPod.tsx
  webapp/src/components/Solid/User/ProfileViewer.tsx
Labels: 🔒 solid, 🔧fixed

#103 Testing branch
  restapi/tests/api.test.ts
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/components/About/About.tsx
Labels: 🔧fixed, 🧪tests

#107 Doc actualization
  docs/01_introduction_and_goals.adoc
  docs/08_concepts.adoc
Labels: 📖 documentation, 🔧fixed

#109 Lee los marcadores y los imprime por consola
  webapp/src/App.tsx
  webapp/src/components/Solid/Friends/WriteInputToPod.tsx
  webapp/src/components/Solid/ReadFromPod.ts
  webapp/src/components/Solid/User/ProfileViewer.tsx
  webapp/src/components/Solid/User/ReadFromPodComponent.tsx
Labels: 🎨 frontend, 🛠️ backend, 🔒 solid

#110 Doc actualization
  docs/01_introduction_and_goals.adoc
Labels: 📖 documentation

#122 Mejorado botón de los marcadores
  webapp/src/components/Map/Markers/ShowMyMarkers.css
  webapp/src/components/Map/Markers/ShowMyMarkers.tsx
  webapp/src/components/Map/OSMap.css
  webapp/src/components/Map/OSMap.tsx
Labels: 🔧fixed

#127 Filters for markers
  webapp/src/components/Map/Markers/Filters/Filter.tsx
  webapp/src/components/Map/Markers/Filters/FilterButton.css
  webapp/src/components/Map/Markers/Filters/Landscape/FilterLandscape.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.tsx
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.css
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.tsx
  webapp/src/components/Map/OSMap.css
  webapp/src/components/Map/OSMap.tsx
Labels: 🔧fixed

#128 Develop to master
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/CommentsPage/CommentsPage.css
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/Markers/Filters/Filter.tsx
  webapp/src/components/Map/Markers/Filters/FilterButton.css
  webapp/src/components/Map/Markers/Filters/Landscape/FilterLandscape.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.tsx
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.css
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.tsx
  webapp/src/components/Map/OSMap.css
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Solid/ReadFromPod.ts
  webapp/src/components/Solid/User/ProfileViewer.tsx
  webapp/src/components/Solid/User/ReadFromPodComponent.tsx
  webapp/src/components/WelcomePage/WelcomePage.css
  webapp/src/components/WelcomePage/WelcomePage.tsx
Labels: 🆘 help wanted

#131 Mostrar marcadores amigos
  .github/workflows/lomap_es6c.yml
  webapp/src/App.tsx
  webapp/src/components/Map/Markers/Filters/Landscape/FilterLandscape.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.tsx
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Pages/LoginPage/LoginPage.css
  webapp/src/components/Pages/LoginPage/LoginPage.tsx
  webapp/src/components/Pages/MainMenu/MainMenu.css
  webapp/src/components/Pages/MainMenu/MainMenu.tsx
  webapp/src/components/Pages/UserPage/UserPage.tsx
  webapp/src/components/Pages/WelcomePage/WelcomePage.css
  webapp/src/components/Pages/WelcomePage/WelcomePage.tsx
  webapp/src/components/Pages/WelcomePage/subcomponents/WelcomeSolid.tsx
  webapp/src/components/Pages/WelcomePage/subcomponents/WelcomeText.tsx
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/ReadFromPod.ts
Labels: 🦾 enhancement, 🔒 solid

#134 Filters y menus
  webapp/src/components/CommentsPage/CommentsPage.css
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/Markers/Filters/Filter.ts
  webapp/src/components/Map/Markers/Filters/FilterButton.css
  webapp/src/components/Map/Markers/Filters/Hamburger/FilterHamburger.css
  webapp/src/components/Map/Markers/Filters/Hamburger/FilterHamburger.tsx
  webapp/src/components/Map/Markers/Filters/Landscape/FilterLandscape.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.tsx
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.css
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.tsx
  webapp/src/components/Map/OSMap.css
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Pages/LoginPage/LoginPage.css
  webapp/src/components/Pages/WelcomePage/WelcomePage.tsx
  webapp/src/components/Solid/Friends/ShowFriendMarkers.tsx
Labels: 🔧fixed

#132 Arreglo test
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/components/Solid/User/UserLogin.tsx
  webapp/src/setupTests.ts
Labels: 🔧fixed, 🧪tests

#138 Permisos de amigos
  .github/workflows/lomap_es6c.yml
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Pages/WelcomePage/WelcomePage.tsx
  webapp/src/components/Solid/Friends/FriendsPermissions.tsx
  webapp/src/components/Solid/Friends/FriendsStyles.css
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/Permissions.ts
  webapp/src/components/Solid/ReadFromPod.ts
  webapp/src/components/Solid/Session.ts
Labels: 🎨 frontend, 🔒 solid, 🔧fixed

#140 Filtrar por amigos concretos
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/Markers/Filters/Friend/FriendsPage.css
  webapp/src/components/Map/Markers/Filters/Friend/FriendsPage.tsx
  webapp/src/components/Map/Markers/Filters/Hamburger/FilterHamburger.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Solid/Friends/ShowFriendMarkers.tsx
Labels: 🔧fixed

#141 Tests components render
  webapp/src/App.test.tsx
Labels: 🔧fixed, 🧪tests

#145 Arreglo documentacion
  docs/01_introduction_and_goals.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
Labels: 📖 documentation, 🔧fixed

#143 Teresa docu
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/05_building_block_view.adoc
Labels: 📖 documentation, 🔧fixed

#144 Pruebas cucumber
  webapp/e2e/features/initial.feature
  webapp/e2e/features/login.feature
  webapp/e2e/jest.config.ts
  webapp/e2e/steps/initial.steps.ts
  webapp/e2e/steps/login.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/tsconfig.json
Labels: 🔧fixed, 🧪tests
