Repository Arquisoft/lomap_es6c, pull requests merged in 2023-05, with the labels that each got.

#153 Texto about - prueba cov
  webapp/src/App.test.tsx
Labels: 🔧fixed, 🧪tests

#154 Doc actualization final saul
  docs/01_introduction_and_goals.adoc
  docs/04_solution_strategy.adoc
  docs/08_concepts.adoc
Labels: 📖 documentation, 🔧fixed

#162 arreglo mock
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.test.jsx
Labels: 🧪tests

#163 Web testing
  webapp/e2e/steps/login.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/public/_redirects
  webapp/src/App.css
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/components/CommentsPage/CommentsPage.css
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/MapIdentifier.tsx
  webapp/src/components/Map/Markers/Filters/FilterButton.css
  webapp/src/components/Map/Markers/Filters/Friend/FriendsPage.css
  webapp/src/components/Map/Markers/Filters/Hamburger/FilterHamburger.css
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.test.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.test.jsx
  webapp/src/components/Map/OSMap.test.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/NavBar/NavBar.css
  webapp/src/components/NavBar/NavBar.tsx
  webapp/src/components/Pages/LoginPage/LoginPage.css
  webapp/src/components/Pages/LoginPage/LoginPage.tsx
  webapp/src/components/Pages/MainMenu/MainMenu.css
  webapp/src/components/Pages/MainMenu/MainMenu.tsx
  webapp/src/components/Pages/UserPage/UserPage.tsx
  webapp/src/components/Pages/WelcomePage/WelcomePage.css
  webapp/src/components/Pages/WelcomePage/WelcomePage.tsx
  webapp/src/components/Pages/WelcomePage/subcomponents/WelcomeSolid.css
  webapp/src/components/Pages/WelcomePage/subcomponents/WelcomeSolid.tsx
  webapp/src/components/Pages/WelcomePage/subcomponents/WelcomeText.tsx
  webapp/src/components/Solid/Friends/RequestFriendship.tsx
  webapp/src/components/Solid/User/UserLogin.tsx
Labels: 🔧fixed, 🧪tests

#168 Develop to master
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/components/CommentsPage/CommentsPage.tsx
  webapp/src/components/Map/MapIdentifier.css
  webapp/src/components/Map/MapIdentifier.tsx
  webapp/src/components/Map/Markers/Filters/Friend/FriendsPage.css
  webapp/src/components/Map/Markers/Filters/Friend/FriendsPage.tsx
  webapp/src/components/Map/Markers/Filters/Hamburger/FilterHamburger.tsx
  webapp/src/components/Map/Markers/Filters/Landscape/FilterLandscape.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.test.tsx
  webapp/src/components/Map/Markers/Filters/Monument/FilterMonument.tsx
  webapp/src/components/Map/Markers/Filters/Restaurant/FilterRestaurant.tsx
  webapp/src/components/Map/Markers/Information/MarkerInfo.css
  webapp/src/components/Map/Markers/Information/MarkerInfo.tsx
  webapp/src/components/Map/Markers/MarkersButton/MarkersButton.tsx
  webapp/src/components/Map/OSMap.css
  webapp/src/components/Map/OSMap.test.tsx
  webapp/src/components/Map/OSMap.tsx
  webapp/src/components/Map/icon.tsx
  webapp/src/components/Solid/Permissions.ts
  webapp/src/components/Solid/ReadFromPod.ts
  webapp/src/components/Solid/Session.ts
  webapp/src/components/Solid/WriteToPod.ts
Labels: invalid

#171 Web testing cov
  sonar-project.properties
  webapp/src/components/Map/OSMap.test.tsx
  webapp/src/components/Map/icon.test.tsx
  webapp/src/components/Solid/ReadFromPod.test.tsx
Labels: 🔧fixed, 🧪tests

#175 Update
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/addMarker.png
  docs/images/business_context.png
  docs/images/filter.png
  docs/images/removeMarker.png
  docs/images/shareMarker.png
  docs/images/technical_context.png
Labels: 📖 documentation
